"""Schemas package."""

from app.schemas.address import AddressCreate, AddressRead, AddressUpdate
from app.schemas.auth import AccessTokenResponse, TokenPayload
from app.schemas.cart import CartItemCreate, CartItemResponse, CartItemUpdate, CartResponse, CartSummary
from app.schemas.category import CategoryCreate, CategoryListItem, CategoryRead, CategorySummary, CategoryUpdate
from app.schemas.common import ApiResponse, PaginatedResponse, PaginationMeta, PaginationParams
from app.schemas.order import (
    AdminOrderListFilters,
    AdminOrderListResponse,
    AssignEmployeeRequest,
    OrderCreateRequest,
    OrderItemResponse,
    OrderListItem,
    OrderResponse,
)
from app.schemas.payment import (
    MercadoPagoCardPaymentCreate,
    MercadoPagoPixPaymentCreate,
    PaymentResponse,
    PaymentWebhookProcessResponse,
)
from app.schemas.product import ProductCreate, ProductListFilters, ProductListItem, ProductRead, ProductUpdate
from app.schemas.product_item import (
    ProductItemCreate,
    ProductItemListFilters,
    ProductItemListItem,
    ProductItemPriceUpdate,
    ProductItemRead,
    ProductItemStockUpdate,
    ProductItemSummary,
    ProductItemUpdate,
)
from app.schemas.shipping import (
    ShippingCalculateRequest,
    ShippingCalculateResponse,
    ShippingDistanceRuleCreate,
    ShippingDistanceRuleResponse,
    ShippingDistanceRuleUpdate,
    ShippingRuleCreate,
    ShippingRuleListFilters,
    ShippingRuleResponse,
    ShippingStoreConfigResponse,
    ShippingStoreConfigUpsert,
    ShippingRuleUpdate,
)
from app.schemas.user import UserRead, UserRegister

__all__ = [
    "AddressCreate",
    "AddressRead",
    "AddressUpdate",
    "AccessTokenResponse",
    "ApiResponse",
    "AdminOrderListFilters",
    "AdminOrderListResponse",
    "AssignEmployeeRequest",
    "CartItemCreate",
    "CartItemResponse",
    "CartItemUpdate",
    "CartResponse",
    "CartSummary",
    "CategoryCreate",
    "CategoryListItem",
    "CategoryRead",
    "CategorySummary",
    "CategoryUpdate",
    "MercadoPagoCardPaymentCreate",
    "MercadoPagoPixPaymentCreate",
    "OrderCreateRequest",
    "OrderItemResponse",
    "OrderListItem",
    "OrderResponse",
    "PaymentResponse",
    "PaymentWebhookProcessResponse",
    "PaginatedResponse",
    "PaginationMeta",
    "PaginationParams",
    "ProductCreate",
    "ProductItemCreate",
    "ProductItemListFilters",
    "ProductItemListItem",
    "ProductItemPriceUpdate",
    "ProductItemRead",
    "ProductItemStockUpdate",
    "ProductItemSummary",
    "ProductItemUpdate",
    "ProductListFilters",
    "ProductListItem",
    "ProductRead",
    "ProductUpdate",
    "ShippingCalculateRequest",
    "ShippingCalculateResponse",
    "ShippingDistanceRuleCreate",
    "ShippingDistanceRuleResponse",
    "ShippingDistanceRuleUpdate",
    "ShippingRuleCreate",
    "ShippingRuleListFilters",
    "ShippingRuleResponse",
    "ShippingStoreConfigResponse",
    "ShippingStoreConfigUpsert",
    "ShippingRuleUpdate",
    "TokenPayload",
    "UserRead",
    "UserRegister",
]
